[package]
name = "grba_front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
profiling-tracy = ["profiling/profile-with-tracy", "tracy-client"]

[dependencies]

# Core Dependencies
grba_core = {path = "../grba_core"}
bincode = "1.3.3"
serde = "1.0.135"

# Profiling
profiling = "1.0.5"
tracy-client = { version = "0.12.6", features = ["enable", "noexit"], optional = true }
