[package]
name = "grba_core"
version = "0.1.0"
edition = "2021"

[features]
default = []
cpu-logging = []

[dev-dependencies]
criterion = "0.3.5"

[dependencies]
# Emulation Development
#modular-bitfield = "0.11.2"
bitfield = "0.13.2"
blip_buf = {git="https://github.com/mvdnes/blip_buf-rs"}
tinyvec = "1.5.1"
num-traits = "0.2"
num-derive = "0.3"
binary-heap-plus = "0.4.1"

# Profiling / Logging
log = "0.4.14"
profiling = "1.0.5"
serde = { version = "1.0.135", features = ["derive"] }

[[bench]]
name = "scheduler"
harness = false
