[package]
name = "grba_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
criterion = "0.3.5"

[dependencies]
# Emulation Development
modular-bitfield = "0.11.2"
blip_buf = {git="https://github.com/mvdnes/blip_buf-rs"}
tinyvec = "1.5.1"

# Profiling / Logging
log = "0.4.14"
profiling = "1.0.5"
serde = { version = "1.0.135", features = ["derive"] }

[[bench]]
name = "scheduler"
harness = false