[package]
name = "grba_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
owo-colors = "3.2.0"
anyhow.workspace = true
grba_core = {path = "../grba_core", features = ["debug-functionality"]}
itertools.workspace = true

# Parsing
memmap2 = "0.5.2"
clap.workspace = true
