name: CI
on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  CI: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA dev
        run: |
          sudo apt update
          sudo apt-get install libasound2-dev libx11-xcb-dev

      - uses: actions/checkout@master

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        id: rust-toolchain
        with:
          toolchain: stable
          profile: default
          override: true

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.2.0

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --no-run

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --verbose

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
